export type Chain = {
  name: string;
  url: string;
  chainType: string;
  chainId: string;
  rpcUrl: string;
  nativeCurrency: {
    name: string;
    symbol: string;
    decimals: number;
  };
  prefix?: number;
  type: string;
  threshold: number;
};

export const chains: Chain[] = [
  {
    name: "Westend",
    url: "westend",
    chainType: "Westend & Parachains",
    chainId: "",
    rpcUrl: "wss://westend-rpc.polkadot.io",
    nativeCurrency: {
      name: "WND",
      symbol: "WND",
      decimals: 12,
    },
    prefix: 42,
    type: "substrate",
    threshold: 10000,
  },
  {
    name: "Westend AssetHub",
    url: "westend-asset-hub",
    chainId: "",
    chainType: "Westend & Parachains",
    rpcUrl: "wss://asset-hub-westend-rpc.dwellir.com",
    nativeCurrency: {
      name: "WND",
      symbol: "WND",
      decimals: 12,
    },
    prefix: 42,
    type: "substrate",
    threshold: 10000,
  },
  {
    name: "Westend BridgeHub",
    url: "westend-bridge-hub",
    chainId: "",
    chainType: "Westend & Parachains",
    rpcUrl: "wss://westend-bridge-hub-rpc.dwellir.com",
    nativeCurrency: {
      name: "WND",
      symbol: "WND",
      decimals: 12,
    },
    prefix: 42,
    type: "substrate",
    threshold: 10000,
  },
  {
    name: "Westend Collectives",
    url: "westend-collectives",
    chainId: "",
    chainType: "Westend & Parachains",
    rpcUrl: "wss://westend-collectives-rpc.dwellir.com",
    nativeCurrency: {
      name: "WND",
      symbol: "WND",
      decimals: 12,
    },
    prefix: 42,
    type: "substrate",
    threshold: 10000,
  },
  {
    name: "Westend Coretime",
    url: "westend-coretime",
    chainId: "",
    chainType: "Westend & Parachains",
    rpcUrl: "wss://sys.ibp.network/coretime-westend",
    nativeCurrency: {
      name: "WND",
      symbol: "WND",
      decimals: 12,
    },
    prefix: 42,
    type: "substrate",
    threshold: 10000,
  },
  {
    name: "Westend People",
    url: "westend-people",
    chainId: "",
    chainType: "Westend & Parachains",
    rpcUrl: "wss://sys.ibp.network/people-westend",
    nativeCurrency: {
      name: "WND",
      symbol: "WND",
      decimals: 12,
    },
    prefix: 42,
    type: "substrate",
    threshold: 10000,
  },
  {
    name: "Rococo",
    url: "rococo",
    chainId: "",
    chainType: "Rococo & Parachains",
    rpcUrl: "wss://rococo-rpc.polkadot.io",
    nativeCurrency: {
      name: "ROC",
      symbol: "ROC",
      decimals: 12,
    },
    prefix: 42,
    type: "substrate",
    threshold: 100000,
  },
  {
    name: "Rococo Asset Hub",
    url: "rococo-asset-hub",
    chainType: "Rococo & Parachains",
    chainId: "",
    rpcUrl: "wss://rococo-asset-hub-rpc.polkadot.io",
    nativeCurrency: {
      name: "ROC",
      symbol: "ROC",
      decimals: 12,
    },
    prefix: 42,
    type: "substrate",
    threshold: 100000,
  },
  {
    name: "Rococo BridgeHub",
    url: "rococo-bridge-hub",
    chainId: "",
    chainType: "Rococo & Parachains",
    rpcUrl: "wss://rococo-bridge-hub-rpc.dwellir.com",
    nativeCurrency: {
      name: "ROC",
      symbol: "ROC",
      decimals: 12,
    },
    prefix: 42,
    type: "substrate",
    threshold: 100000,
  },
  {
    name: "Rococo Contracts",
    url: "rococo-contracts",
    chainId: "",
    chainType: "Rococo & Parachains",
    rpcUrl: "wss://rococo-contracts-rpc.polkadot.io",
    nativeCurrency: {
      name: "ROC",
      symbol: "ROC",
      decimals: 12,
    },
    prefix: 42,
    type: "substrate",
    threshold: 100000,
  },
  {
    name: "Rococo Coretime",
    url: "rococo-coretime",
    chainId: "",
    chainType: "Rococo & Parachains",
    rpcUrl: "wss://rococo-coretime-rpc.polkadot.io",
    nativeCurrency: {
      name: "ROC",
      symbol: "ROC",
      decimals: 12,
    },
    prefix: 42,
    type: "substrate",
    threshold: 100000,
  },
  {
    name: "Encointer",
    url: "encointer",
    chainId: "",
    chainType: "Rococo & Parachains",
    rpcUrl: "wss://rococo.api.encointer.org",
    nativeCurrency: {
      name: "ROC",
      symbol: "ROC",
      decimals: 12,
    },
    prefix: 42,
    type: "substrate",
    threshold: 100000,
  },
  {
    name: "Rococo People",
    url: "rococo-people",
    chainId: "",
    chainType: "Rococo & Parachains",
    rpcUrl: "wss://rococo-people-rpc.polkadot.io",
    nativeCurrency: {
      name: "ROC",
      symbol: "ROC",
      decimals: 12,
    },
    prefix: 42,
    type: "substrate",
    threshold: 100000,
  },
  /*
  {
    name: "",
    url: "rococo-amplitude",
    chainId: "",
    chainType: "Rococo & Parachains",
    rpcUrl: "wss://rpc-foucoco.pendulumchain.tech",
    nativeCurrency: {
      name: "",
      symbol: "",
      decimals: ,
    },
    prefix: ,
    type: "substrate",
    threshold: ,
  },
  {
    name: "",
    url: "rococo-aventus",
    chainId: "",
    chainType: "Rococo & Parachains",
    rpcUrl: "wss://public-rpc.public-testnet.aventus.io",
    nativeCurrency: {
      name: "",
      symbol: "",
      decimals: ,
    },
    prefix: ,
    type: "substrate",
    threshold: ,
  },
  {
    name: "",
    url: "rococo-basilisk",
    chainId: "",
    chainType: "Rococo & Parachains",
    rpcUrl: "wss://basilisk-rococo-rpc.play.hydration.cloud",
    nativeCurrency: {
      name: "",
      symbol: "",
      decimals: ,
    },
    prefix: ,
    type: "substrate",
    threshold: ,
  },
  {
    name: "",
    url: "rococo-curio",
    chainId: "",
    chainType: "Rococo & Parachains",
    rpcUrl: "wss://testnet.parachain.curioinvest.com/",
    nativeCurrency: {
      name: "",
      symbol: "",
      decimals: ,
    },
    prefix: ,
    type: "substrate",
    threshold: ,
  },
  {
    name: "",
    url: "rococo-frequency",
    chainId: "",
    chainType: "Rococo & Parachains",
    rpcUrl: "wss://frequency-rococo-rpc.dwellir.com",
    nativeCurrency: {
      name: "",
      symbol: "",
      decimals: ,
    },
    prefix: ,
    type: "substrate",
    threshold: ,
  },
  {
    name: "",
    url: "roroco-laos",
    chainId: "",
    chainType: "Rococo & Parachains",
    rpcUrl: "wss://rpc.giedi.laosfoundation.io",
    nativeCurrency: {
      name: "",
      symbol: "",
      decimals: ,
    },
    prefix: ,
    type: "substrate",
    threshold: ,
  },
  {
    name: "",
    url: "rococo-hydradx",
    chainId: "",
    chainType: "Rococo & Parachains",
    rpcUrl: "wss://hydradx-rococo-rpc.play.hydration.cloud",
    nativeCurrency: {
      name: "",
      symbol: "",
      decimals: ,
    },
    prefix: ,
    type: "substrate",
    threshold: ,
  },
  {
    name: "",
    url: "rococo-hyperbridge",
    chainId: "",
    chainType: "Rococo & Parachains",
    rpcUrl: "wss://hyperbridge-gargantua-rpc.blockops.network",
    nativeCurrency: {
      name: "",
      symbol: "",
      decimals: ,
    },
    prefix: ,
    type: "substrate",
    threshold: ,
  },
  {
    name: "",
    url: "rococo-litentry",
    chainId: "",
    chainType: "Rococo & Parachains",
    rpcUrl: "wss://rpc.rococo-parachain.litentry.io",
    nativeCurrency: {
      name: "",
      symbol: "",
      decimals: ,
    },
    prefix: ,
    type: "substrate",
    threshold: ,
  },
  {
    name: "",
    url: "rococo-mangata",
    chainId: "",
    chainType: "Rococo & Parachains",
    rpcUrl: "wss://collator-01-ws-rococo.mangata.online",
    nativeCurrency: {
      name: "",
      symbol: "",
      decimals: ,
    },
    prefix: ,
    type: "substrate",
    threshold: ,
  },
  {
    name: "",
    url: "rococo-md5",
    chainId: "",
    chainType: "Rococo & Parachains",
    rpcUrl: "wss://c1md5.hashed.network",
    nativeCurrency: {
      name: "",
      symbol: "",
      decimals: ,
    },
    prefix: ,
    type: "substrate",
    threshold: ,
  },
  {
    name: "",
    url: "rococo-muse",
    chainId: "",
    chainType: "Rococo & Parachains",
    rpcUrl: "wss://rococo-muse-rpc.polkadot.io",
    nativeCurrency: {
      name: "",
      symbol: "",
      decimals: ,
    },
    prefix: ,
    type: "substrate",
    threshold: ,
  },
  {
    name: "",
    url: "rococo-neuro-web",
    chainId: "",
    chainType: "Rococo & Parachains",
    rpcUrl: "wss://parachain-testnet-rpc.origin-trail.network/",
    nativeCurrency: {
      name: "",
      symbol: "",
      decimals: ,
    },
    prefix: ,
    type: "substrate",
    threshold: ,
  },
  {
    name: "",
    url: "chainoli",
    chainId: "",
    chainType: "Rococo & Parachains",
    rpcUrl: "OLI",
    nativeCurrency: {
      name: "",
      symbol: "",
      decimals: ,
    },
    prefix: ,
    type: "substrate",
    threshold: ,
  },
  {
    name: "",
    url: "rococo-open-zeppelin",
    chainId: "",
    chainType: "Rococo & Parachains",
    rpcUrl: "OpenZeppelin Runtime Template",
    nativeCurrency: {
      name: "",
      symbol: "",
      decimals: ,
    },
    prefix: ,
    type: "substrate",
    threshold: ,
  },
  {
    name: "",
    url: "rococo-pangolin",
    chainId: "",
    chainType: "Rococo & Parachains",
    rpcUrl: "wss://pangolin-rpc.darwinia.network",
    nativeCurrency: {
      name: "",
      symbol: "",
      decimals: ,
    },
    prefix: ,
    type: "substrate",
    threshold: ,
  },
  {
    name: "",
    url: "rococo-ewx",
    chainId: "",
    chainType: "Rococo & Parachains",
    rpcUrl: "wss://public-rpc.testnet.energywebx.com/",
    nativeCurrency: {
      name: "",
      symbol: "",
      decimals: ,
    },
    prefix: ,
    type: "substrate",
    threshold: ,
  },
  {
    name: "",
    url: "rococo-phala",
    chainId: "",
    chainType: "Rococo & Parachains",
    rpcUrl: "wss://rhala-node.phala.network/ws",
    nativeCurrency: {
      name: "",
      symbol: "",
      decimals: ,
    },
    prefix: ,
    type: "substrate",
    threshold: ,
  },
  {
    name: "",
    url: "rococo-kilt",
    chainId: "",
    chainType: "Rococo & Parachains",
    rpcUrl: "wss://rilt.kilt.io",
    nativeCurrency: {
      name: "",
      symbol: "",
      decimals: ,
    },
    prefix: ,
    type: "substrate",
    threshold: ,
  },
  {
    name: "",
    url: "rococo-subsocial",
    chainId: "",
    chainType: "Rococo & Parachains",
    rpcUrl: "wss://rco-para.subsocial.network",
    nativeCurrency: {
      name: "",
      symbol: "",
      decimals: ,
    },
    prefix: ,
    type: "substrate",
    threshold: ,
  },
  {
    name: "",
    url: "rococo-sora",
    chainId: "",
    chainType: "Rococo & Parachains",
    rpcUrl: "wss://ws.parachain-collator-1.c1.stg1.sora2.soramitsu.co.jp",
    nativeCurrency: {
      name: "",
      symbol: "",
      decimals: ,
    },
    prefix: ,
    type: "substrate",
    threshold: ,
  },
  {
    name: "",
    url: "t0rn",
    chainId: "",
    chainType: "Rococo & Parachains",
    rpcUrl: "wss://rpc.t0rn.io",
    nativeCurrency: {
      name: "",
      symbol: "",
      decimals: ,
    },
    prefix: ,
    type: "substrate",
    threshold: ,
  },
  {
    name: "",
    url: "rococo-watr",
    chainId: "",
    chainType: "Rococo & Parachains",
    rpcUrl: "wss://rpc.dev.watr.org",
    nativeCurrency: {
      name: "",
      symbol: "",
      decimals: ,
    },
    prefix: ,
    type: "substrate",
    threshold: ,
  },
  {
    name: "",
    url: "rococo-yerba",
    chainId: "",
    chainType: "Rococo & Parachains",
    rpcUrl: "wss://rpc.dev.yerba.network",
    nativeCurrency: {
      name: "",
      symbol: "",
      decimals: ,
    },
    prefix: ,
    type: "substrate",
    threshold: ,
  },
  {
    name: "",
    url: "rococo-zeitgeist",
    chainId: "",
    chainType: "Rococo & Parachains",
    rpcUrl: "wss://bsr.zeitgeist.pm",
    nativeCurrency: {
      name: "",
      symbol: "",
      decimals: ,
    },
    prefix: ,
    type: "substrate",
    threshold: ,
  },
  */
  {
    name: "Paseo",
    url: "paseo",
    chainId: "",
    chainType: "Paseo & Parachains",
    rpcUrl: "wss://paseo.rpc.amforc.com",
    nativeCurrency: {
      name: "PAS",
      symbol: "PAS",
      decimals: 10,
    },
    prefix: 42,
    type: "substrate",
    threshold: 100000,
  },
  {
    name: "Paseo AssetHub",
    url: "paseo-asset-hub",
    chainId: "",
    chainType: "Paseo & Parachains",
    rpcUrl: "wss://asset-hub-paseo-rpc.dwellir.com",
    nativeCurrency: {
      name: "PAS",
      symbol: "PAS",
      decimals: 10,
    },
    prefix: 42,
    type: "substrate",
    threshold: 100000,
  },
  {
    name: "Bifrost Paseo",
    url: "bifrost-paseo",
    chainId: "",
    chainType: "Paseo & Parachains",
    rpcUrl: "wss://bifrost-rpc.paseo.liebi.com/ws",
    nativeCurrency: {
      name: "BNC",
      symbol: "BNC",
      decimals: 12,
    },
    prefix: 6,
    type: "substrate",
    threshold: 5000,
  },
  {
    name: "Frequency Paseo",
    url: "frequency-paseo",
    chainId: "",
    chainType: "Paseo & Parachains",
    rpcUrl: "wss://0.rpc.testnet.amplica.io",
    nativeCurrency: {
      name: "XRQCY",
      symbol: "XRQCY",
      decimals: 8,
    },
    prefix: 42,
    type: "substrate",
    threshold: 150000,
  },
  {
    name: "Hyperbridge (Gargantua)",
    url: "hyperbridge",
    chainId: "",
    chainType: "Paseo & Parachains",
    rpcUrl: "wss://hyperbridge-paseo-rpc.blockops.network",
    nativeCurrency: {
      name: "tNAND",
      symbol: "tNAND",
      decimals: 12,
    },
    prefix: 42,
    type: "substrate",
    threshold: 100000,
  },
  {
    name: "Integritee Testnet",
    url: "integritee",
    chainId: "",
    chainType: "Paseo & Parachains",
    rpcUrl: "wss://paseo.api.integritee.network",
    nativeCurrency: {
      name: "TEER",
      symbol: "TEER",
      decimals: 12,
    },
    prefix: 13,
    type: "substrate",
    threshold: 100,
  },
  {
    name: "KILT Peregrine",
    url: "kilt",
    chainId: "",
    chainType: "Paseo & Parachains",
    rpcUrl: "wss://peregrine.kilt.io/parachain-public-ws/",
    nativeCurrency: {
      name: "PILT",
      symbol: "PILT",
      decimals: 15,
    },
    prefix: 38,
    type: "substrate",
    threshold: 150000,
  },
  {
    name: "Laos Omega Testnet",
    url: "laos-omega",
    chainId: "",
    chainType: "Paseo & Parachains",
    rpcUrl: "wss://rpc.laosomega.laosfoundation.io",
    nativeCurrency: {
      name: "OMEGA",
      symbol: "OMEGA",
      decimals: 18,
    },
    prefix: 42,
    type: "substrate",
    threshold: 1000000,
  },
  {
    name: "Parachain Hades (Nodle)",
    chainId: "",
    chainType: "Paseo & Parachains",
    url: "nodle-paradis",
    rpcUrl: "wss://node-6957502816543653888.lh.onfinality.io/ws?apikey=09b04494-3139-4b57-a5d1-e1c4c18748ce",
    nativeCurrency: {
      name: "notNODL",
      symbol: "notNODL",
      decimals: 11,
    },
    prefix: 37,
    type: "substrate",
    threshold: 1000,
  },
  {
    name: "Pop Network",
    url: "pop-network",
    chainId: "",
    chainType: "Paseo & Parachains",
    rpcUrl: "wss://rpc1.paseo.popnetwork.xyz",
    nativeCurrency: {
      name: "PAS",
      symbol: "PAS",
      decimals: 10,
    },
    prefix: 42,
    type: "substrate",
    threshold: 100000,
  },
  /*
  {
    name: "",
    url: "aleph-testnet",
    chainId: "",
    chainType: "Solochains",
    rpcUrl: "wss://ws.test.azero.dev",
    nativeCurrency: {
      name: "",
      symbol: "",
      decimals: ,
    },
    prefix: ,
    type: "substrate",
    threshold: ,
  },
  {
    name: "",
    url: "analog-testnet",
    chainId: "",
    chainType: "Solochains",
    rpcUrl: "wss://rpc.testnet.analog.one",
    nativeCurrency: {
      name: "",
      symbol: "",
      decimals: ,
    },
    prefix: ,
    type: "substrate",
    threshold: ,
  },
  */
  {
    name: "Beresheet (Edgeware)",
    url: "beresheet",
    chainId: "",
    chainType: "Solochains",
    rpcUrl: "wss://beresheet.jelliedowl.net",
    nativeCurrency: {
      name: "tEDG",
      symbol: "tEDG",
      decimals: 18,
    },
    prefix: 7,
    type: "substrate",
    threshold: 200000,
  },
  /*
  {
    name: "",
    url: "thebifrost-testnet",
    chainId: "",
    chainType: "Solochains",
    rpcUrl: "wss://public-01.testnet.bifrostnetwork.com/wss",
    nativeCurrency: {
      name: "",
      symbol: "",
      decimals: ,
    },
    prefix: ,
    type: "substrate",
    threshold: ,
  },
  {
    name: "",
    url: "chainflip",
    chainId: "",
    chainType: "Solochains",
    rpcUrl: "wss://archive.perseverance.chainflip.io",
    nativeCurrency: {
      name: "",
      symbol: "",
      decimals: ,
    },
    prefix: ,
    type: "substrate",
    threshold: ,
  },
  {
    name: "",
    url: "creditcoin-classic-testnet",
    chainId: "",
    chainType: "Solochains",
    rpcUrl: "wss://rpc.testnet.creditcoin.network/ws",
    nativeCurrency: {
      name: "",
      symbol: "",
      decimals: ,
    },
    prefix: ,
    type: "substrate",
    threshold: ,
  },
  {
    name: "",
    url: "creditcoin-testnet",
    chainId: "",
    chainType: "Solochains",
    rpcUrl: "wss://rpc.cc3-testnet.creditcoin.network/ws",
    nativeCurrency: {
      name: "",
      symbol: "",
      decimals: ,
    },
    prefix: ,
    type: "substrate",
    threshold: ,
  },
  {
    name: "",
    url: "dancebox",
    chainId: "",
    chainType: "Solochains",
    rpcUrl: "wss://dancebox.tanssi-api.network",
    nativeCurrency: {
      name: "",
      symbol: "",
      decimals: ,
    },
    prefix: ,
    type: "substrate",
    threshold: ,
  },
  {
    name: "",
    url: "debio-testnet",
    chainId: "",
    chainType: "Solochains",
    rpcUrl: "wss://gateway.testnet.octopus.network/debionetwork/554976cbb180f676f188abe14d63ca24",
    nativeCurrency: {
      name: "",
      symbol: "",
      decimals: ,
    },
    prefix: ,
    type: "substrate",
    threshold: ,
  },
  {
    name: "",
    url: "encointer",
    chainId: "",
    chainType: "Solochains",
    rpcUrl: "wss://gesell.encointer.org",
    nativeCurrency: {
      name: "",
      symbol: "",
      decimals: ,
    },
    prefix: ,
    type: "substrate",
    threshold: ,
  },
  {
    name: "",
    url: "harmonie",
    chainId: "",
    chainType: "Solochains",
    rpcUrl: "wss://harmonie-endpoint-02.allfeat.io",
    nativeCurrency: {
      name: "",
      symbol: "",
      decimals: ,
    },
    prefix: ,
    type: "substrate",
    threshold: ,
  },
  {
    name: "",
    url: "interlay-testnet",
    chainId: "",
    chainType: "Solochains",
    rpcUrl: "wss://api-testnet.interlay.io/parachain/",
    nativeCurrency: {
      name: "",
      symbol: "",
      decimals: ,
    },
    prefix: ,
    type: "substrate",
    threshold: ,
  },
  {
    name: "",
    url: "ipse",
    chainId: "",
    chainType: "Solochains",
    rpcUrl: "wss://testnet-china.ipse.io",
    nativeCurrency: {
      name: "",
      symbol: "",
      decimals: ,
    },
    prefix: ,
    type: "substrate",
    threshold: ,
  },
  {
    name: "",
    url: "jur",
    chainId: "",
    chainType: "Solochains",
    rpcUrl: "wss://testnet.jur.io",
    nativeCurrency: {
      name: "",
      symbol: "",
      decimals: ,
    },
    prefix: ,
    type: "substrate",
    threshold: ,
  },
  {
    name: "",
    url: "kintsugi-testnet",
    chainId: "",
    chainType: "Solochains",
    rpcUrl: "wss://api-dev-kintsugi.interlay.io/parachain",
    nativeCurrency: {
      name: "",
      symbol: "",
      decimals: ,
    },
    prefix: ,
    type: "substrate",
    threshold: ,
  },
  {
    name: "",
    url: "liberland",
    chainId: "",
    chainType: "Solochains",
    rpcUrl: "wss://testchain.liberland.org",
    nativeCurrency: {
      name: "",
      symbol: "",
      decimals: ,
    },
    prefix: ,
    type: "substrate",
    threshold: ,
  },
  {
    name: "",
    url: "logion",
    chainId: "",
    chainType: "Solochains",
    rpcUrl: "wss://test-para-rpc01.logion.network",
    nativeCurrency: {
      name: "",
      symbol: "",
      decimals: ,
    },
    prefix: ,
    type: "substrate",
    threshold: ,
  },
  {
    name: "",
    url: "moonbase-alpha",
    chainId: "",
    chainType: "Solochains",
    rpcUrl: "wss://moonbase-alpha.public.blastapi.io",
    nativeCurrency: {
      name: "",
      symbol: "",
      decimals: ,
    },
    prefix: ,
    type: "substrate",
    threshold: ,
  },
  {
    name: "",
    url: "myriad-tesnet",
    chainId: "",
    chainType: "Solochains",
    rpcUrl: "wss://gateway.testnet.octopus.network/myriad/8f543a1c219f14d83c0faedefdd5be6e",
    nativeCurrency: {
      name: "",
      symbol: "",
      decimals: ,
    },
    prefix: ,
    type: "substrate",
    threshold: ,
  },
  {
    name: "",
    url: "opal",
    chainId: "",
    chainType: "Solochains",
    rpcUrl: "wss://ws-opal.unique.network",
    nativeCurrency: {
      name: "",
      symbol: "",
      decimals: ,
    },
    prefix: ,
    type: "substrate",
    threshold: ,
  },
  {
    name: "",
    url: "phala",
    chainId: "",
    chainType: "Solochains",
    rpcUrl: "wss://poc6.phala.network/ws",
    nativeCurrency: {
      name: "",
      symbol: "",
      decimals: ,
    },
    prefix: ,
    type: "substrate",
    threshold: ,
  },
  {
    name: "",
    url: "polymesh",
    chainId: "",
    chainType: "Solochains",
    rpcUrl: "wss://testnet-rpc.polymesh.live",
    nativeCurrency: {
      name: "",
      symbol: "",
      decimals: ,
    },
    prefix: ,
    type: "substrate",
    threshold: ,
  },
  {
    name: "",
    url: "shibuya",
    chainId: "",
    chainType: "Solochains",
    rpcUrl: "wss://rpc.shibuya.astar.network",
    nativeCurrency: {
      name: "",
      symbol: "",
      decimals: ,
    },
    prefix: ,
    type: "substrate",
    threshold: ,
  },
  {
    name: "",
    url: "sora-substrate",
    chainId: "",
    chainType: "Solochains",
    rpcUrl: "wss://ws.framenode-1.s1.stg1.sora2.soramitsu.co.jp",
    nativeCurrency: {
      name: "",
      symbol: "",
      decimals: ,
    },
    prefix: ,
    type: "substrate",
    threshold: ,
  },
  {
    name: "",
    url: "subspace-gemini-1",
    chainId: "",
    chainType: "Solochains",
    rpcUrl: "wss://eu.gemini-1b.subspace.network/ws",
    nativeCurrency: {
      name: "",
      symbol: "",
      decimals: ,
    },
    prefix: ,
    type: "substrate",
    threshold: ,
  },
  {
    name: "",
    url: "subspace-gemini-2a",
    chainId: "",
    chainType: "Solochains",
    rpcUrl: "wss://eu-0.gemini-2a.subspace.network/ws",
    nativeCurrency: {
      name: "",
      symbol: "",
      decimals: ,
    },
    prefix: ,
    type: "substrate",
    threshold: ,
  },
  {
    name: "",
    url: "subspace-gemini-3f",
    chainId: "",
    chainType: "Solochains",
    rpcUrl: "wss://rpc-1.gemini-3f.subspace.network/ws",
    nativeCurrency: {
      name: "",
      symbol: "",
      decimals: ,
    },
    prefix: ,
    type: "substrate",
    threshold: ,
  },
  {
    name: "",
    url: "subspace-gemini-3g",
    chainId: "",
    chainType: "Solochains",
    rpcUrl: "wss://rpc-1.gemini-3g.subspace.network/ws",
    nativeCurrency: {
      name: "",
      symbol: "",
      decimals: ,
    },
    prefix: ,
    type: "substrate",
    threshold: ,
  },
  {
    name: "",
    url: "subspace-gemini-3g-nova",
    chainId: "",
    chainType: "Solochains",
    rpcUrl: "wss://nova.gemini-3g.subspace.network/ws",
    nativeCurrency: {
      name: "",
      symbol: "",
      decimals: ,
    },
    prefix: ,
    type: "substrate",
    threshold: ,
  },
  {
    name: "",
    url: "subspace-gemini-3h",
    chainId: "",
    chainType: "Solochains",
    rpcUrl: "wss://rpc-0.gemini-3h.subspace.network/ws",
    nativeCurrency: {
      name: "",
      symbol: "",
      decimals: ,
    },
    prefix: ,
    type: "substrate",
    threshold: ,
  },
  {
    name: "",
    url: "subspace-gemini-3h-nova",
    chainId: "",
    chainType: "Solochains",
    rpcUrl: "wss://nova-0.gemini-3h.subspace.network/ws",
    nativeCurrency: {
      name: "",
      symbol: "",
      decimals: ,
    },
    prefix: ,
    type: "substrate",
    threshold: ,
  },
  {
    name: "",
    url: "ternoa-alphanet",
    chainId: "",
    chainType: "Solochains",
    rpcUrl: "wss://alphanet.ternoa.com",
    nativeCurrency: {
      name: "",
      symbol: "",
      decimals: ,
    },
    prefix: ,
    type: "substrate",
    threshold: ,
  },
  {
    name: "",
    url: "vara-testnet",
    chainId: "",
    chainType: "Solochains",
    rpcUrl: "wss://testnet.vara.network",
    nativeCurrency: {
      name: "",
      symbol: "",
      decimals: ,
    },
    prefix: ,
    type: "substrate",
    threshold: ,
  },
  {
    name: "",
    url: "zero-alphaville",
    chainId: "",
    chainType: "Solochains",
    rpcUrl: "wss://rpc.dev.gamedao.net",
    nativeCurrency: {
      name: "",
      symbol: "",
      decimals: ,
    },
    prefix: ,
    type: "substrate",
    threshold: ,
  },
  */
  {
    name: "Beresheet BereEVM (Edgeware)",
    url: "beresheet-bereevm",
    chainId: "2022",
    chainType: "Solochains",
    rpcUrl: "https://beresheet-evm.jelliedowl.net",
    nativeCurrency: {
      name: "tEDG",
      symbol: "tEDG",
      decimals: 18,
    },
    type: "evm",
    threshold: 200000,
  },
  {
    name: "Bifrost Solo testnet EVM",
    url: "thebifrost-testnet-evm",
    chainType: "Solochains",
    chainId: "49088",
    rpcUrl: "https://public-01.testnet.bifrostnetwork.com/rpc",
    nativeCurrency: {
      name: "BFC",
      symbol: "BFC",
      decimals: 18,
    },
    type: "evm",
    threshold: 5000,
  },
  {
    name: "Moonbase Alpha",
    url: "moonbase-alpha",
    chainId: "1287",
    chainType: "Solochains",
    rpcUrl: "https://rpc.testnet.moonbeam.network",
    nativeCurrency: {
      name: "DEV",
      symbol: "DEV",
      decimals: 18,
    },
    type: "evm",
    threshold: 100000,
  },
  {
    name: 'Tangle EVM',
    url: 'tangle-testnet-evm',
    chainId: '3799',
    chainType: 'Solochains',
    rpcUrl: 'https://testnet-rpc.tangle.tools',
    nativeCurrency: {
      name: 'tTNT',
      symbol: 'tTNT',
      decimals: 18
    },
    type: 'evm',
    threshold: 100000,
  },
];
